name: Deploy to WebServer

on: [push]

jobs:
  Deploy-to-WebServer:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The time is $(TZ='America/New_York' date)."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Spell Check
        uses: rojopolis/spellcheck-github-actions@0.34.0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Update Date Before Deploying
        run: |
          sed -i "s/INSERTDATE/$(TZ='America/New_York' date '+%A %b %d %Y')/g" index.html
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/.github/, /.wordlist.txt, /.spellcheck.yml, /LICENSE, /README.md, /dictionary.dic, /.git/, /.gitattributes"
      - run: echo "This job's status is ${{ job.status }}."